# Numpy -  multidimensional data arrays

Credits:J.R. Johansson 


In [40]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [41]:
import numpy as np

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [42]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [43]:

# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3.0,4]])

M

array([[1., 2.],
       [3., 4.]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [44]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [45]:
v.shape

(4,)

In [46]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [47]:
M.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [48]:
np.shape(M)

(2, 2)

In [49]:
np.size(M)

4

So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [50]:
M.dtype

dtype('float64')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [51]:
M[0,0] = "hello"

ValueError: could not convert string to float: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [ ]:
import numpy as np
M = np.array([[1, 2], [3, 4]], dtype=complex)

M
M.dtype

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

In [ ]:
M = np.array([[1, 2], [3, 4]], dtype='int16')
#M = np.array([[1, 2], [3, 4]], dtype=np.int16)
M

### Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [ ]:
# create a range

x = np.arange(0, 10, 3) # arguments: start, stop, step

x

In [ ]:
x = np.arange(-1, 1, 0.1)

x

#### linspace

In [ ]:
# using linspace, both end points ARE included
import numpy as np
np.linspace(0, 1, 25)

#### random data

In [ ]:
from numpy import random

In [ ]:
# uniform random numbers in [0,1]
import numpy as np
from numpy import random
random.rand(0,1)

In [ ]:
# standard normal distributed random numbers
random.randn(5,5)


#### diag

In [ ]:
# a diagonal matrix
np.diag([1,2,3,5])

In [ ]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=3) 

In [ ]:
# matrix creation by array input 
a = np.array([  [1, 21, 30], 
                [63 ,434, 3], 
                [54, 54, 56]]) 

print("Main Diagnol elements : \n", np.diag(a,+0), "\n") 

print("Diagnol above main diagnol : \n", np.diag(a, 1), "\n") 

print("Diagnol below main diagnol : \n", np.diag(a, -1)) 

print("Right Diagnol elements : \n",np.diag(np.fliplr(a)))
print("Right Diagnol elements : \n",np.diag(np.fliplr(a),-1))

#### zeros and ones

In [ ]:
np.zeros((3,3))

In [ ]:
np.ones((3,3))

## File I/O

### Comma-separated values (CSV)

A very common file format for data files is comma-separated values (CSV), or related formats such as TSV (tab-separated values). To read data from such files into Numpy arrays we can use the `numpy.genfromtxt` function. For example, 

In [ ]:
data = np.genfromtxt('../Exercise/baseball.csv',delimiter=',')

In [ ]:
data

In [ ]:
fig, ax = plt.subplots(figsize=(14,4))
ax.scatter(data[:,5], data[:,3])
ax.axis('tight')
ax.set_title('Age vs Height')
ax.set_xlabel('Age')
ax.set_ylabel('Height');

Using `numpy.savetxt` we can store a Numpy array to a file in CSV format:

In [ ]:
M = random.rand(3,3)                                                                                                                                    

M

In [ ]:
np.savetxt("random-matrix.csv", M)                                                                                                       

In [ ]:
np.savetxt("random-matrix.csv", M, fmt='%.2f') # fmt specifies the format

!type random-matrix.csv

### Numpy's native file format

Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`:

In [ ]:
np.save("random-matrix.npy", M)

In [ ]:
np.load("random-matrix.npy")

## More properties of the numpy arrays

In [ ]:
M.itemsize # bytes per element

In [ ]:
M.nbytes # number of bytes

In [ ]:
M.ndim # number of dimensions

## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [67]:
# v is a vector, and has only one dimension, taking one index
v = np.array([1,2,3,4])

v[0]

1

In [68]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

4

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [69]:
M

array([[1, 2],
       [3, 4]], dtype=int16)

In [70]:
M[0]

array([1, 2], dtype=int16)

The same thing can be achieved with using `:` instead of an index: 

In [71]:
M[1, :] # row 1

array([3, 4], dtype=int16)

In [74]:
M[:,1] # column 1

array([2, 4], dtype=int16)

We can assign new values to elements in an array using indexing:

In [ ]:
M[0,0] = 1

In [ ]:
M

In [ ]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [ ]:
M

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [ ]:
A = np.array([1,2,3,4,5])
A

In [ ]:
A[1:3]

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [ ]:
A[1:3] = [7]

A

We can omit any of the three parameters in `M[lower:upper:step]`:

In [ ]:
A[::] # lower, upper, step all take the default values

In [ ]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

In [ ]:
A[:3] # first three elements

In [ ]:
A[3:] # elements from index 3

Negative indices counts from the end of the array (positive index from the begining):

In [ ]:
A = np.array([1,2,3,4,5])

In [ ]:
A[-1] # the last element in the array

In [ ]:
A[-3:] # the last three elements

Index slicing works exactly the same way for multidimensional arrays:

In [75]:
A = np.array([[m for n in range(5)] for m in range(5)])

A

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [76]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [77]:
# a block from the original array
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [80]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [81]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [82]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [83]:
B = np.array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [84]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [85]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [86]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [87]:
mask = (5  < x)* (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [88]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [89]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14], dtype=int64),)

In [90]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([5.5, 6. , 6.5, 7. ])

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [91]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

In [92]:
np.diag(A, 1)

array([ 1, 12, 23, 34])

### take

The `take` function is similar to fancy indexing described above:

In [93]:
v2 = np.arange(-3,3)
v2

array([-3, -2, -1,  0,  1,  2])

In [94]:
row_indices = [1, 3, 5]
v2[row_indices] # fancy indexing

array([-2,  0,  2])

In [95]:
v2.take(row_indices)

array([-2,  0,  2])

But `take` also works on lists and other objects:

In [96]:
np.take([-3, -2, -1,  0,  1,  2], row_indices)

array([-2,  0,  2])

### choose

Constructs an array by picking elements from several arrays:

In [97]:
which = [0, 1, 0,2]
choices = [[-2,-3,-4,-5], [1,2,3,4],[6,7,8,9]]
    
np.choose(which, choices)

array([-2,  2, -4,  9])